/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Elijah
 */
public class AdminUserForm extends javax.swing.JFrame {

    //private String IDname;
    private AdminMainMenu mm = new AdminMainMenu();
    
    /**
     * Creates new form AdminUserForm
     */
    public AdminUserForm() throws SQLException {
        //String IDname = mm.ID;
        this.setSize(900, 700);
        this.setResizable(false);
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((size.width - this.getSize().width) / 2, (size.height - this.getSize().height) / 2);
        JDBC();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws SQLException {

        MainPanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        UserNameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        IDLabel = new javax.swing.JLabel();
        MidPanel = new javax.swing.JPanel();
        PasswordPanel = new javax.swing.JPanel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordVariable = new javax.swing.JLabel();
        EmailPanel = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        EmailVariable = new javax.swing.JLabel();
        GenderPanel = new javax.swing.JPanel();
        GenderLabel = new javax.swing.JLabel();
        GenderVariable = new javax.swing.JLabel();
        ContactPanel = new javax.swing.JPanel();
        ContactLabel = new javax.swing.JLabel();
        ContactVariable = new javax.swing.JLabel();
        DepartmentPanel = new javax.swing.JPanel();
        DepartmentLabel = new javax.swing.JLabel();
        DepartmentVariable = new javax.swing.JLabel();
        PinPanel = new javax.swing.JPanel();
        PinLabel = new javax.swing.JLabel();
        PinVariable = new javax.swing.JLabel();
        LevelPanel = new javax.swing.JPanel();
        LevelLabel = new javax.swing.JLabel();
        LevelVariable = new javax.swing.JLabel();
        SubjectPanel = new javax.swing.JPanel();
        SubjectLabel = new javax.swing.JLabel();
        SubjectListPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SubjectListField = new javax.swing.JTextArea();
        ButtonsPanel = new javax.swing.JPanel();
        OkButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserNameLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        IDLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        PasswordLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PasswordLabel.setText("Password:");

        PasswordVariable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout PasswordPanelLayout = new javax.swing.GroupLayout(PasswordPanel);
        PasswordPanel.setLayout(PasswordPanelLayout);
        PasswordPanelLayout.setHorizontalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(PasswordLabel)
                .addGap(48, 48, 48)
                .addComponent(PasswordVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PasswordPanelLayout.setVerticalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasswordPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        EmailLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        EmailLabel.setText("E-mail:");

        EmailVariable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout EmailPanelLayout = new javax.swing.GroupLayout(EmailPanel);
        EmailPanel.setLayout(EmailPanelLayout);
        EmailPanelLayout.setHorizontalGroup(
            EmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmailPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(EmailLabel)
                .addGap(68, 68, 68)
                .addComponent(EmailVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmailPanelLayout.setVerticalGroup(
            EmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(EmailLabel)
                .addComponent(EmailVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        GenderLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        GenderLabel.setText("Gender: ");

        GenderVariable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout GenderPanelLayout = new javax.swing.GroupLayout(GenderPanel);
        GenderPanel.setLayout(GenderPanelLayout);
        GenderPanelLayout.setHorizontalGroup(
            GenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenderPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(GenderLabel)
                .addGap(56, 56, 56)
                .addComponent(GenderVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GenderPanelLayout.setVerticalGroup(
            GenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(GenderLabel)
                .addComponent(GenderVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ContactLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ContactLabel.setText("Contact #: ");

        ContactVariable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout ContactPanelLayout = new javax.swing.GroupLayout(ContactPanel);
        ContactPanel.setLayout(ContactPanelLayout);
        ContactPanelLayout.setHorizontalGroup(
            ContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(ContactLabel)
                .addGap(38, 38, 38)
                .addComponent(ContactVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContactPanelLayout.setVerticalGroup(
            ContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ContactLabel)
                .addComponent(ContactVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DepartmentLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        DepartmentLabel.setText("Department: ");

        DepartmentVariable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout DepartmentPanelLayout = new javax.swing.GroupLayout(DepartmentPanel);
        DepartmentPanel.setLayout(DepartmentPanelLayout);
        DepartmentPanelLayout.setHorizontalGroup(
            DepartmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepartmentPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(DepartmentLabel)
                .addGap(27, 27, 27)
                .addComponent(DepartmentVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DepartmentPanelLayout.setVerticalGroup(
            DepartmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepartmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(DepartmentLabel)
                .addComponent(DepartmentVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PinLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PinLabel.setText("Security Pin:");

        PinVariable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout PinPanelLayout = new javax.swing.GroupLayout(PinPanel);
        PinPanel.setLayout(PinPanelLayout);
        PinPanelLayout.setHorizontalGroup(
            PinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PinPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(PinLabel)
                .addGap(35, 35, 35)
                .addComponent(PinVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PinPanelLayout.setVerticalGroup(
            PinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(PinLabel)
                .addComponent(PinVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LevelLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LevelLabel.setText("Level:");

        LevelVariable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout LevelPanelLayout = new javax.swing.GroupLayout(LevelPanel);
        LevelPanel.setLayout(LevelPanelLayout);
        LevelPanelLayout.setHorizontalGroup(
            LevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LevelPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(LevelLabel)
                .addGap(69, 69, 69)
                .addComponent(LevelVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LevelPanelLayout.setVerticalGroup(
            LevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LevelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(LevelLabel)
                .addComponent(LevelVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SubjectLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        SubjectLabel.setText("Subjects:");

        SubjectListField.setColumns(20);
        SubjectListField.setRows(5);
        jScrollPane1.setViewportView(SubjectListField);

        javax.swing.GroupLayout SubjectListPanelLayout = new javax.swing.GroupLayout(SubjectListPanel);
        SubjectListPanel.setLayout(SubjectListPanelLayout);
        SubjectListPanelLayout.setHorizontalGroup(
            SubjectListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectListPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        SubjectListPanelLayout.setVerticalGroup(
            SubjectListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectListPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout SubjectPanelLayout = new javax.swing.GroupLayout(SubjectPanel);
        SubjectPanel.setLayout(SubjectPanelLayout);
        SubjectPanelLayout.setHorizontalGroup(
            SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(SubjectLabel)
                .addGap(50, 50, 50)
                .addComponent(SubjectListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SubjectPanelLayout.setVerticalGroup(
            SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanelLayout.createSequentialGroup()
                .addGroup(SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubjectLabel)
                    .addComponent(SubjectListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        OkButton.setText("OK");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        EditButton.setText("Edit Info");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    EditButtonActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminUserForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        javax.swing.GroupLayout ButtonsPanelLayout = new javax.swing.GroupLayout(ButtonsPanel);
        ButtonsPanel.setLayout(ButtonsPanelLayout);
        ButtonsPanelLayout.setHorizontalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ButtonsPanelLayout.setVerticalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OkButton)
                    .addComponent(EditButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout MidPanelLayout = new javax.swing.GroupLayout(MidPanel);
        MidPanel.setLayout(MidPanelLayout);
        MidPanelLayout.setHorizontalGroup(
            MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EmailPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GenderPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContactPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DepartmentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LevelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SubjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MidPanelLayout.setVerticalGroup(
            MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MidPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(PasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContactPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DepartmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LevelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MidPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SubjectListField.setEditable(false);
        setupUserInfo();
        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    
    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        this.dispose();
    }
    
    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                           
        // TODO add your handling code here:
        edituser = new AdminEditUserForm();
        edituser.setVisible(true);
        this.dispose();
    }  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminUserForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminUserForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private void JDBC() throws SQLException
    {
        url="jdbc:mysql://localhost:3306/cpe_database";
        prop = new Properties();
        prop.setProperty("user", "root");
        prop.setProperty("password", "");
        d = new com.mysql.jdbc.Driver();
        con = d.connect(url, prop);
        if(con==null)   
        {
            //System.out.println("Connection Failed");
            return;
        }
        else
        {
            //System.out.println("Connected");
        }
    }
    
    private void setupUserInfo() throws SQLException
    {
        String subjectlist = "";
        stat = con.createStatement();
        result = stat.executeQuery("SELECT * FROM users WHERE ID = '" + mm.ID + "';");
        while(result.next())
        {
            IDLabel.setText(result.getString("ID"));
            UserNameLabel.setText(result.getString("Name"));
            ContactVariable.setText(result.getString("contact"));
            DepartmentVariable.setText(result.getString("department"));
            EmailVariable.setText(result.getString("email"));
            GenderVariable.setText(result.getString("gender"));
            if(Integer.parseInt(result.getString("level")) == 0)
            {
                LevelVariable.setText("Faculty");
            }
            else if(Integer.parseInt(result.getString("level")) == 1)
            {
                LevelVariable.setText("Quality Coordinator");
            }
            else if(Integer.parseInt(result.getString("level")) == 2)
            {
                LevelVariable.setText("Department Coordinator");
            }
            else if(Integer.parseInt(result.getString("level")) == 3)
            {
                LevelVariable.setText("Administrator");
            }
            PasswordVariable.setText(result.getString("Password"));
            PinVariable.setText(result.getString("pin"));
            if(Integer.parseInt(result.getString("level")) == 0)
            {
                for(int i = 1; i <= 10; i++)
                {
                    if(result.getString("subject" + i).equals("na") || result.getString("subject" + i).equals("NA"))
                    {
                        break;
                    }
                    else
                    {
                        subjectlist = subjectlist + result.getString("subject" + i);
                        if(i<10)
                        {
                            subjectlist = subjectlist + "\n";
                        }
                    }
                }
                //String subjectlist = result.getString("subject1") + "\n" + result.getString("subject2")
                        //+ "\n" + result.getString("subject3") + "\n" + result.getString("subject4") +
                       // "\n" + result.getString("subject5") + "\n" + result.getString("subject6") + 
                        //"\n" + result.getString("subject7") + "\n" + result.getString("subject8") + 
                        //"\n" + result.getString("subject9") + "\n" + result.getString("subject10");
                
                SubjectListField.setText(subjectlist);
            }
            else
            {
                SubjectListField.setText("No applicable subjects");
            }
        }
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JPanel ContactPanel;
    private javax.swing.JLabel ContactVariable;
    private javax.swing.JLabel DepartmentLabel;
    private javax.swing.JPanel DepartmentPanel;
    private javax.swing.JLabel DepartmentVariable;
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel EmailPanel;
    private javax.swing.JLabel EmailVariable;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JPanel GenderPanel;
    private javax.swing.JLabel GenderVariable;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel LevelLabel;
    private javax.swing.JPanel LevelPanel;
    private javax.swing.JLabel LevelVariable;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MidPanel;
    private javax.swing.JButton OkButton;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JLabel PasswordVariable;
    private javax.swing.JLabel PinLabel;
    private javax.swing.JPanel PinPanel;
    private javax.swing.JLabel PinVariable;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JTextArea SubjectListField;
    private javax.swing.JPanel SubjectListPanel;
    private javax.swing.JPanel SubjectPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration     
    
    //Variable declaration for mysql properties
    private String url;
    private Properties prop;
    private Driver d;
    private Connection con;
    private Statement stat;
    private ResultSet result;
    //End of variable declaration
    
    private AdminEditUserForm edituser;
}
