/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Elijah
 */
public class AdminEditCourse extends javax.swing.JFrame {

    /**
     * Creates new form AdminEditCourse
     */
    private AdminMainMenu mm = new AdminMainMenu();
    public AdminEditCourse() throws SQLException {
        this.setSize(900, 700);
        this.setResizable(false);
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((size.width - this.getSize().width) / 2, (size.height - this.getSize().height) / 2);
        JDBC();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        NamePanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        DetailPanel = new javax.swing.JPanel();
        DetailLabel = new javax.swing.JLabel();
        DetailField = new javax.swing.JTextField();
        DepartmentPanel = new javax.swing.JPanel();
        DepartmentLabel = new javax.swing.JLabel();
        DepartmentField = new javax.swing.JTextField();
        SOPanel = new javax.swing.JPanel();
        SOLabel = new javax.swing.JLabel();
        SOField = new javax.swing.JTextField();
        WorkPanel = new javax.swing.JPanel();
        WorkLabel = new javax.swing.JLabel();
        WorkField = new javax.swing.JTextField();
        PercentPanel = new javax.swing.JPanel();
        PercentLabel = new javax.swing.JLabel();
        PercentField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        EditButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Title.setText("Edit Course:");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NameLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        NameLabel.setText("Course Name: ");

        NameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout NamePanelLayout = new javax.swing.GroupLayout(NamePanel);
        NamePanel.setLayout(NamePanelLayout);
        NamePanelLayout.setHorizontalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamePanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        NamePanelLayout.setVerticalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamePanelLayout.createSequentialGroup()
                .addComponent(NameLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        DetailLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        DetailLabel.setText("Details:");

        DetailField.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout DetailPanelLayout = new javax.swing.GroupLayout(DetailPanel);
        DetailPanel.setLayout(DetailPanelLayout);
        DetailPanelLayout.setHorizontalGroup(
            DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(DetailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DetailField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        DetailPanelLayout.setVerticalGroup(
            DetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailPanelLayout.createSequentialGroup()
                .addComponent(DetailLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(DetailField, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        DepartmentLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        DepartmentLabel.setText("Department:");

        javax.swing.GroupLayout DepartmentPanelLayout = new javax.swing.GroupLayout(DepartmentPanel);
        DepartmentPanel.setLayout(DepartmentPanelLayout);
        DepartmentPanelLayout.setHorizontalGroup(
            DepartmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepartmentPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(DepartmentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepartmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        DepartmentPanelLayout.setVerticalGroup(
            DepartmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DepartmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(DepartmentLabel)
        );

        SOLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        SOLabel.setText("Student Outcomes:");

        SOField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout SOPanelLayout = new javax.swing.GroupLayout(SOPanel);
        SOPanel.setLayout(SOPanelLayout);
        SOPanelLayout.setHorizontalGroup(
            SOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SOPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(SOLabel)
                .addGap(27, 27, 27)
                .addComponent(SOField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        SOPanelLayout.setVerticalGroup(
            SOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SOPanelLayout.createSequentialGroup()
                .addComponent(SOLabel)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(SOField)
        );

        WorkLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        WorkLabel.setText("Work:");

        WorkField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout WorkPanelLayout = new javax.swing.GroupLayout(WorkPanel);
        WorkPanel.setLayout(WorkPanelLayout);
        WorkPanelLayout.setHorizontalGroup(
            WorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(WorkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WorkField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        WorkPanelLayout.setVerticalGroup(
            WorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkPanelLayout.createSequentialGroup()
                .addComponent(WorkLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(WorkField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        PercentLabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PercentLabel.setText("Percent:");

        PercentField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout PercentPanelLayout = new javax.swing.GroupLayout(PercentPanel);
        PercentPanel.setLayout(PercentPanelLayout);
        PercentPanelLayout.setHorizontalGroup(
            PercentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PercentPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(PercentLabel)
                .addGap(91, 91, 91)
                .addComponent(PercentField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PercentPanelLayout.setVerticalGroup(
            PercentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PercentPanelLayout.createSequentialGroup()
                .addComponent(PercentLabel)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(PercentField)
        );

        EditButton.setText("Edit Course");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    EditButtonActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminEditCourse.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(EditButton)
                .addGap(49, 49, 49)
                .addComponent(CancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DepartmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SOPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(WorkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PercentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(NamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DepartmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SOPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WorkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PercentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                           
        // TODO add your handling code here:
        if(DepartmentField.getText().equals("") || DetailField.getText().equals("") || NameField.getText().equals("") || PercentField.getText().equals("") || SOField.getText().equals("") || WorkField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Insufficient information to edit course.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            stat = con.createStatement();
            stat.executeUpdate("UPDATE classes SET Detail = '" + DetailField.getText() + "' WHERE Name = '" + mm.course + "';");
            stat.executeUpdate("UPDATE classes SET Department = '" + DepartmentField.getText() + "' WHERE Name = '" + mm.course + "';");
            stat.executeUpdate("UPDATE classes SET SO = '" + SOField.getText() + "' WHERE Name = '" + mm.course + "';");
            stat.executeUpdate("UPDATE classes SET work = '" + WorkField.getText() + "' WHERE Name = '" + mm.course + "';");
            stat.executeUpdate("UPDATE classes SET percent = '" + PercentField.getText() + "' WHERE Name = '" + mm.course + "';");
            stat.executeUpdate("UPDATE classes SET Name = '" + NameField.getText() + "' WHERE Name = '" + mm.course + "';");
            JOptionPane.showMessageDialog(null, "Editing Course Success", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }                                          

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        this.dispose();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminEditCourse().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminEditCourse.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void JDBC() throws SQLException
    {
        url="jdbc:mysql://localhost:3306/cpe_database";
        prop = new Properties();
        prop.setProperty("user", "root");
        prop.setProperty("password", "");
        d = new com.mysql.jdbc.Driver();
        con = d.connect(url, prop);
        if(con==null)   
        {
            //System.out.println("Connection Failed");
            return;
        }
        else
        {
            //System.out.println("Connected");
        }
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DepartmentField;
    private javax.swing.JLabel DepartmentLabel;
    private javax.swing.JPanel DepartmentPanel;
    private javax.swing.JTextField DetailField;
    private javax.swing.JLabel DetailLabel;
    private javax.swing.JPanel DetailPanel;
    private javax.swing.JButton EditButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JTextField PercentField;
    private javax.swing.JLabel PercentLabel;
    private javax.swing.JPanel PercentPanel;
    private javax.swing.JTextField SOField;
    private javax.swing.JLabel SOLabel;
    private javax.swing.JPanel SOPanel;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JTextField WorkField;
    private javax.swing.JLabel WorkLabel;
    private javax.swing.JPanel WorkPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration     
    
    //Variable declaration for mysql properties
    private String url;
    private Properties prop;
    private Driver d;
    private Connection con;
    private Statement stat;
    private ResultSet result;
    //End of variable declaration
}
