/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sofweng;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author PauloSenires
 */
public class classList extends javax.swing.JFrame {
    String subject="ENGALG1";
    String section="EJ";
    String[] students;
    JLabel[] studentLabelList;
    JLabel[] finalGradesList;
    JLabel[] soGradesList;
    String[] finalGrades;
    String[] soGrades;
    int noStudents = 0;
    int count=1;
    /**
     * Creates new form classList
     */
    public classList() throws SQLException {
        initComponents();
        fetchStudents(subject,section);
    }
    public classList(String subject,String section) throws SQLException {
        initComponents();
        this.subject = subject;
        this.section = section;
        fetchStudents(subject,section);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subLabel = new javax.swing.JLabel();
        secLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        displayPane = new javax.swing.JScrollPane();
        displayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subLabel.setText("Subject");

        secLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        secLabel.setText("Section");

        jLabel3.setText("ID number");

        jLabel4.setText("Final Grade");

        jLabel5.setText("SO Grades");

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        displayPane.setViewportView(displayPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subLabel)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPane, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subLabel)
                    .addComponent(secLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayPane, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(classList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(classList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(classList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(classList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new classList().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(classList.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public void fetchStudents(String subject, String section) throws SQLException{
        secLabel.setText(section);
        subLabel.setText(subject);
        try {
            displayPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
            students = new String[45];
            finalGrades = new String[45];
            soGrades = new String[45];
            java.lang.Class.forName("com.mysql.jdbc.Driver");
            
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cpe_database?" + "user=root&password=");
            
            for(int i=1;i<11;i++){
            PreparedStatement pst = conn.prepareStatement("Select * from students where subject"+i+" = ? AND section"+i+" = ?");
            pst.setString(1,subject);
            pst.setString(2,section);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {      
            students[count] = rs.getString("ID");
            finalGrades[count]=rs.getString("grade"+i);
            soGrades[count]=rs.getString("so"+i);
            count++;
            
            
            }
            }
            System.out.println(count);
            studentLabelList = new JLabel[count];
            finalGradesList = new JLabel[count];
            soGradesList = new JLabel[count];
            displayPanel.setLayout(new GridLayout(5,1));
            for (int i=0;i<(count);i++) {
                JLabel studentLabel = new JLabel(students[i]);
                studentLabelList[i]=studentLabel;
                studentLabel.setVisible(true);
               displayPanel.add(studentLabel);
               
               JLabel finalGradesLabel = new JLabel(finalGrades[i]);
                finalGradesList[i]=finalGradesLabel;
                studentLabel.setVisible(true);
               displayPanel.add(finalGradesLabel);
               
               JLabel soGradesLabel = new JLabel(soGrades[i]);
                soGradesList[i]=soGradesLabel;
                studentLabel.setVisible(true);
               displayPanel.add(soGradesLabel);
            }
            
            displayPane.validate();
            displayPane.repaint();
        } 
            catch (ClassNotFoundException ex) {
            Logger.getLogger(classList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane displayPane;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel secLabel;
    private javax.swing.JLabel subLabel;
    // End of variables declaration//GEN-END:variables
}
