package sofweng;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*; 
/**
 *
 * @author iwcnrlee1
 */
public class QualityCoordinator extends javax.swing.JFrame {

    /**
     * Creates new form QualityCoordinator
     */
    ArrayList<String> courseList=new ArrayList<String>();
    ArrayList<String> subjectList=new ArrayList<String>();
    public int count;
    JButton courseBtn, subjectBtn;
    int btnHeight= 45; //Height of Buttons
    int space=0;
    Font font = new Font("Arial", Font.BOLD,18);
    public QualityCoordinator() {
        initComponents();
        this.setSize(900, 700);
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((size.width-this.getSize().width)/2,(size.height-this.getSize().height)/2);
        courseList.addAll(Arrays.asList(fetchCourseList()));
        viewCourseList(courseList,0);
        
    }
    
    public String[] fetchCourseList(){
        String[] list = {"CHE","CIV","ECE","IE","MEM","MEE"};
        return list;
    }
    
    public String[] fetchSubjectList(int count){
        String[] list = {"ENGALG1","ENGTRIG","DIFFCAL","ANAGEOM","SOCTEC2","MPROSYS","INTECAL"};
        return list;
    }
    
    
    
    public void viewCourseList(ArrayList list, int open){
        MainPane.removeAll();
        MainPane.revalidate();
        MainPane.repaint();
        ScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        for (int i=1;i<list.size()+1;i++){
            courseBtn = new JButton(list.get(i-1)+" Department");
            courseBtn.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    for (int j=0;j<list.size();j++){
                        if(e.getActionCommand().contains(""+list.get(j))){
                            if(count==j+1) count=0;
                            else count=j+1;
                            viewCourseList(list,count);
                        }
                    }
                }
            });
            MainPane.add(courseBtn);
            courseBtn.setFont(font);
            courseBtn.setHorizontalAlignment(JLabel.LEFT);
            courseBtn.setSize(MainPane.getWidth()-50, btnHeight);
            courseBtn.setLocation(courseBtn.getX(),courseBtn.getY()+space);
            space=space+btnHeight;
            courseBtn.setVisible(true);
            if(count==i) generateSubjects(i);
        }
        Dimension size = new Dimension(900,space);
        MainPane.setPreferredSize(size);
        space=0;
        
    }
    
    public void generateSubjects(int count){
        subjectList.clear();
        subjectList.addAll(Arrays.asList(fetchSubjectList(count)));
        for (int i=1;i<subjectList.size()+1;i++){
            subjectBtn = new JButton(subjectList.get(i-1));
                subjectBtn.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        for (int j=0;j<subjectList.size()-1;j++){
                            if(e.getActionCommand().contains(""+subjectList.get(j))){
                                System.out.println(e.getActionCommand());
                            }
                        }
                    }
                });
                MainPane.add(subjectBtn);
                subjectBtn.setFont(font);
                subjectBtn.setHorizontalAlignment(JLabel.LEFT);
                subjectBtn.setSize(MainPane.getWidth()-100, btnHeight);
                subjectBtn.setLocation(subjectBtn.getX()+50,subjectBtn.getY()+space);
                space=space+btnHeight;
                subjectBtn.setVisible(true);
        }
    }
    
    public boolean isCourseComplete(){
        return false;
    }
    
    public void courseSummary(){
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        MainPane = new javax.swing.JPanel();
        HeaderPane = new javax.swing.JPanel();
        Greeting = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 700));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));

        ScrollPane.setBorder(null);
        ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        MainPane.setPreferredSize(new java.awt.Dimension(498, 1000));

        javax.swing.GroupLayout MainPaneLayout = new javax.swing.GroupLayout(MainPane);
        MainPane.setLayout(MainPaneLayout);
        MainPaneLayout.setHorizontalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        MainPaneLayout.setVerticalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        ScrollPane.setViewportView(MainPane);

        Greeting.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Greeting.setText("Welcome, Quality Coordinator");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gokongwei College of Engineering");

        javax.swing.GroupLayout HeaderPaneLayout = new javax.swing.GroupLayout(HeaderPane);
        HeaderPane.setLayout(HeaderPaneLayout);
        HeaderPaneLayout.setHorizontalGroup(
            HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(527, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Greeting)
                .addGap(20, 20, 20))
        );
        HeaderPaneLayout.setVerticalGroup(
            HeaderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Greeting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ScrollPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HeaderPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QualityCoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QualityCoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QualityCoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QualityCoordinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QualityCoordinator().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Greeting;
    private javax.swing.JPanel HeaderPane;
    private javax.swing.JPanel MainPane;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
